config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # See all tasks
  root to: "tasks#index"

  # Create a tasks
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  # See details about one tasks
  get "tasks/:id", to: "tasks#show", as: :task

  # Update a tasks
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"


  # Destroy a tasks
  delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all

  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @tasks = Task.new
  end

  def create
    @tasks = Task.new(tasks_params)
    @tasks.save
    redirect_to root_path
  end

  def edit
    @tasks = Task.find(params[:id])
  end

  def update
    @tasks = Task.find(params[:id])
    @tasks.update(tasks_params)
    redirect_to root_path
  end

  def destroy
    @tasks = Task.find(params[:id])
    @tasks.destroy
    redirect_to root_path, status: :see_other
  end

  private
  # to prevent input forgery

  def tasks_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @tasks do |f| %>
<div class="card">
  <div class="card-body">
    <div class ="mb-3">
      <%= f.label :title, {class: "form-label"} %>
      <%= f.text_field :title, {class:"form-control"} %>
    </div>

    <div class ="mb-3">
      <%= f.label :details, {class: "form-label"} %>
      <%= f.text_field :details, {class: "form-control"} %>
    </div>

    <%= f.submit%>

  </div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form", task: @tasks %>

app/views/tasks/index.html.erb
<div class="container-fluid">
  <div class ="row">
    <h3>Display All Task</h3>
    <div class="card">
      <ul class ="list-group" style="list-style-type:none">
        <% @tasks.each do |task| %>
        <li class="list-group-item">
          <input class="form-check-input me-1" type="checkbox" value="1" name=>
          <%= link_to task.title, task_path(task) %>
          
          <%= link_to "Delete",
            task_path(@tasks),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete this task"}
          %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= link_to "+ Add a new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<div class ="container justify-content-center">
  <div class="row text-align-center">
    <%= render "form", task: @tasks %>
  </div>

<%= link_to "Cancel", root_path %>

app/views/tasks/show.html.erb
<!-- app/views/task/show.html.erb -->
<h2><%= @tasks.title %></h2>
<p><%= @tasks.details %></p>


<%= link_to "Back to list", root_path %>